name: Tests

on:
  push:
    branches:
      - main
      - "!dependabot/**"
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE_COV: 20 # The Node.js version to run coveralls on

jobs:
  test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [18, 20]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.architecture }}
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm run jest

      - name: Run Coveralls
        uses: coverallsapp/github-action@v2
        if: startsWith(matrix.os, 'ubuntu') && matrix.node == env.NODE_COV
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
